@startuml

[*] --> 注册 
注册: 手机号
注册: 密码
注册: 验证码
注册 -> 忘记密码
注册 -> 注册协议
注册 --> 登录

登录 --> 首页
登录 -> 数据
登录 -> 写文章
登录 -> 学习
登录 -> 用户

首页: 头部banner故事分享
首页: 讨论分析
首页: 新闻列表
首页: 比赛列表

首页 --> 文章详情

文章详情: 评价体系
文章详情: 计分体系

写文章: 创建讨论
写文章: 发文章

学习: 预测比赛结果
学习: 学习视频
学习: 技战术教学
学习: 是真的吗

用户: 收藏文章
用户: 关注讨论话题或者文章
用户: Air值
用户: 图集
用户: 设置
用户: 募捐

用户 --> 设置
用户 --> 图集
用户 --> 收藏列表
用户 --> 募捐项目
用户 --> 关注列表

设置: 信息更改
设置: 相关协议
设置: 版本
设置: 关于

数据 --> 球员
数据 --> 球队

球员 --> 资料
球员 --> 最近数据
球员 --> 新闻

球队 --> 新闻和介绍
球队 --> 赛程
球队 --> 教练及球员

@enduml